export const SEED_CARS: string[] = [
  "Chery QQ",
  "Coradir Tito",
  "Chrysler Neon",
  "Fiat Marea",
  "Ford Galaxy",
  "Rover",
  "Daewoo Espero",
  "Citroen C4 Cactus",
  "Citroen C4 Lounge",
  "Renault Koleos",
  "Fiat Idea",
  "Dodge/Chrysler Stratus",
  "Chevrolet Lumina",
  "Renault Latitude",
  "Renault Symbol",
  "Ford Orion",
  "Peugeot Hoggar",
  "Citroen C5",
  "Rover 620",
  "Citroen Picasso",
  "Fiat Linea",
  "Chrysler PT Cruiser",
  "Renault Twingo",
  "Ford S-Max",
  "Peugeot 807",
  "Ford Fiesta Powershift",
  "Toyota Innova",
  "Chevrolet Spark",
  "Renault Laguna",
  "Citroen C4 Picasso",
  "Fiat Stilo",
  "Lada Niva",
  "SsangYong Korando",
  "SsangYong Musso",
  "Alfa Romeo 159",
  "Volkswagen Up",
  "Saab 9000",
  "Daihatsu Charade",
  "Volkswagen Polo Classic",
  "Citroen C3 Picasso",
  "Citroen Xsara",
  "Volkswagen Caddy",
  "TATA Sumo",
  "Daewoo Lanos",
  "Hyundai S Coupe",
  "Nissan Teana",
  "Hyundai Galloper",
  "Hyundai Elantra",
  "Citroen Xantia",
  "Ford Courier",
  "Ford Mondeo",
  "Volvo",
  "Volkswagen Sharan",
  "Kia Opirus",
  "Volkswagen Pointer",
  "Lada 2107",
  "Oltcit",
  "Aleko",
  "Dacia",
  "Tavria",
  "Toyota Avensis",
  "Volvo 460",
  "Chevrolet Lumina APV",
  "Seat Marbella",
  "Renault Safrane",
  "Saab 9-3",
  "Jaguar",
  "Hyundai Coupe",
  "Chevrolet Vectra",
  "Fiat Tempra",
  "Audi A6",
  "Chevrolet Captiva",
  "Volvo C30",
  "Volkswagen Suran",
  "Hyundai Atos",
  "Saab",
  "Peugeot 605",
  "Fiat Multipla",
  "Lifan X60",
  "SsangYong Kyron",
  "Lifan 620",
  "Geely CK",
  "BMW Serie 5 E60",
  "Peugeot 407",
  "Chery Tiggo",
  "Chevrolet Zafira",
  "Subaru Tribeca",
  "Citroen C6",
  "Alfa Romeo 156",
  "BAIC D20",
  "Ford Edsel",
  "Kia Sorento",
  "Honda City",
  "Fiat Qubo",
  "Suzuki Grand Vitara",
  "Renault Fluence",
  "Toyota Fielder",
  "Mitsubishi Galant",
  "Volkswagen Santana",
];

export function searchCars(query: string): string[] {
  if (!query || query.length < 1) return SEED_CARS.slice(0, 8);
  const q = query.toLowerCase();
  return SEED_CARS.filter((car) =>
    car.toLowerCase().includes(q)
  ).slice(0, 8);
}
